[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
  "pip install fastapi uvicorn[standard]"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "pip install -e ."
]

[start]
cmd = "python mcp_multi_transport_proxy.py"
