[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install fastapi uvicorn[standard]",
    "pip install 'mcp[cli]>=1.13.1'"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "pip install -e ."
]

[start]
cmd = ". /opt/venv/bin/activate && python mcp_multi_transport_proxy.py"
